version: "3.5"

services:

  nginx:
    image: nginx:latest
    ports:
     - "8181:80"
    volumes:
     - ./app:/var/www/html
     - ./configs/nginx:/etc/nginx/conf.d
     - ./logs/nginx:/var/log/nginx

  php-fpm:
    build:
      context: php-fpm
    volumes:
    - ./app:/var/www/html

  php:
    build:
      context: php
    ports:
     - 81:80
    volumes:
     - ./app:/var/www/html

  mardiadb:
    image: mariadb:11.6
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: testdb
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    volumes:
    - ./databases/mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
     - 8081:80
    environment:
      PMA_HOST: mardiadb
      PMA_USER: test_user
      PMA_PASSWORD: test_pass

volumes:
  db_data: